// Auto-generated by generate_module_indexes.py
import svg from './advanced/svg/registry-item.json' with { type: 'json' }
import led_number from './advanced/led-number/registry-item.json' with { type: 'json' }
import svg_editor from './advanced/svg-editor/registry-item.json' with { type: 'json' }
import text_editor from './advanced/text-editor/registry-item.json' with { type: 'json' }
import widgets_media from './advanced/widgets-media/registry-item.json' with { type: 'json' }
import qrcode from './advanced/qrcode/registry-item.json' with { type: 'json' }
import time from './advanced/time/registry-item.json' with { type: 'json' }
import show_attachment from './advanced/show-attachment/registry-item.json' with { type: 'json' }
import upload_attachment from './advanced/upload-attachment/registry-item.json' with { type: 'json' }
import flop_number from './advanced/flop-number/registry-item.json' with { type: 'json' }
import widget_pdf_preivew from './advanced/widget-pdf-preivew/registry-item.json' with { type: 'json' }
import custom_pagination from './advanced/custom-pagination/registry-item.json' with { type: 'json' }
import player from './advanced/player/registry-item.json' with { type: 'json' }
import model_3d_geometry_cylinder from './3d/model-3d-geometry-cylinder/registry-item.json' with { type: 'json' }
import model_3d_card from './3d/model-3d-card/registry-item.json' with { type: 'json' }
import model_3d_geometry_sphere from './3d/model-3d-geometry-sphere/registry-item.json' with { type: 'json' }
import model_3d_mesh from './3d/model-3d-mesh/registry-item.json' with { type: 'json' }
import model_3d_points from './3d/model-3d-points/registry-item.json' with { type: 'json' }
import model_3d_layout_3d from './3d/model-3d-layout-3d/registry-item.json' with { type: 'json' }
import model_3d_geometry_plane from './3d/model-3d-geometry-plane/registry-item.json' with { type: 'json' }
import model_3d_geometry_cone from './3d/model-3d-geometry-cone/registry-item.json' with { type: 'json' }
import model_3d_geometry_box from './3d/model-3d-geometry-box/registry-item.json' with { type: 'json' }
import model_3d_geometry_circle from './3d/model-3d-geometry-circle/registry-item.json' with { type: 'json' }
import model_3d from './3d/model-3d/registry-item.json' with { type: 'json' }
import model_3d_geometry_tube from './3d/model-3d-geometry-tube/registry-item.json' with { type: 'json' }
import video_widget from './video/video-widget/registry-item.json' with { type: 'json' }
import button_widget from './video/button-widget/registry-item.json' with { type: 'json' }
import video_periods_widget from './video/video-periods-widget/registry-item.json' with { type: 'json' }
import time_axis from './video/time-axis/registry-item.json' with { type: 'json' }
import isc_video from './video/isc-video/registry-item.json' with { type: 'json' }
import review_view_components from './video/review-view-components/registry-item.json' with { type: 'json' }
import form_widget from './form/form-widget/registry-item.json' with { type: 'json' }
import form from './form/form/registry-item.json' with { type: 'json' }
import time_widget from './form/time-widget/registry-item.json' with { type: 'json' }
import schema_form from './form/schema-form/registry-item.json' with { type: 'json' }
import form_date_range from './form/form-date-range/registry-item.json' with { type: 'json' }
import form_date from './form/form-date/registry-item.json' with { type: 'json' }
import form_slider from './form/form-slider/registry-item.json' with { type: 'json' }
import user_form_widget from './form/user-form-widget/registry-item.json' with { type: 'json' }
import form_area from './form/form-area/registry-item.json' with { type: 'json' }
import form_rate from './form/form-rate/registry-item.json' with { type: 'json' }
import table_schema_form from './form/table-schema-form/registry-item.json' with { type: 'json' }
import form_switch from './form/form-switch/registry-item.json' with { type: 'json' }
import form_checkbox from './form/form-checkbox/registry-item.json' with { type: 'json' }
import form_input from './form/form-input/registry-item.json' with { type: 'json' }
import form_input_number from './form/form-input-number/registry-item.json' with { type: 'json' }
import form_upload from './form/form-upload/registry-item.json' with { type: 'json' }
import form_radio from './form/form-radio/registry-item.json' with { type: 'json' }
import form_map from './form/form-map/registry-item.json' with { type: 'json' }
import form_select from './form/form-select/registry-item.json' with { type: 'json' }
import warning_button from './page-elements/warning-button/registry-item.json' with { type: 'json' }
import reg_widget_component from './page-elements/reg-widget-component/registry-item.json' with { type: 'json' }
import logout_component from './page-elements/logout-component/registry-item.json' with { type: 'json' }
import warning_audio from './page-elements/warning-audio/registry-item.json' with { type: 'json' }
import new_menu from './page-elements/new-menu/registry-item.json' with { type: 'json' }
import warning_bar from './page-elements/warning-bar/registry-item.json' with { type: 'json' }
import auth_info_cards from './page-elements/auth-info-cards/registry-item.json' with { type: 'json' }
import scale_button from './page-elements/scale-button/registry-item.json' with { type: 'json' }
import service_time from './page-elements/service-time/registry-item.json' with { type: 'json' }
import log_out from './page-elements/log-out/registry-item.json' with { type: 'json' }
import message from './page-elements/message/registry-item.json' with { type: 'json' }
import front_menu from './page-elements/front-menu/registry-item.json' with { type: 'json' }
import nav_tabs from './page-elements/nav-tabs/registry-item.json' with { type: 'json' }
import profile from './page-elements/profile/registry-item.json' with { type: 'json' }
import warning_notification from './page-elements/warning-notification/registry-item.json' with { type: 'json' }
import user_menu from './page-elements/user-menu/registry-item.json' with { type: 'json' }
import user_name from './page-elements/user-name/registry-item.json' with { type: 'json' }
import load_component from './page-elements/load-component/registry-item.json' with { type: 'json' }
import language_change_widget from './page-elements/language-change-widget/registry-item.json' with { type: 'json' }
import change_password from './page-elements/change-password/registry-item.json' with { type: 'json' }
import log_table_widget from './page-elements/log-table-widget/registry-item.json' with { type: 'json' }
import chart_radar from './chart/chart-radar/registry-item.json' with { type: 'json' }
import chart_bar from './chart/chart-bar/registry-item.json' with { type: 'json' }
import data_view_chart from './chart/data-view-chart/registry-item.json' with { type: 'json' }
import chart_map from './chart/chart-map/registry-item.json' with { type: 'json' }
import chart_line from './chart/chart-line/registry-item.json' with { type: 'json' }
import chart_gauge from './chart/chart-gauge/registry-item.json' with { type: 'json' }
import chart_pie from './chart/chart-pie/registry-item.json' with { type: 'json' }
import report_reportwidget from './chart/report-reportwidget/registry-item.json' with { type: 'json' }
import chart_pictorial_bar from './chart/chart-pictorial-bar/registry-item.json' with { type: 'json' }
import chart_mix from './chart/chart-mix/registry-item.json' with { type: 'json' }
import chart_scatter from './chart/chart-scatter/registry-item.json' with { type: 'json' }
import chart_liquid_fill from './chart/chart-liquid-fill/registry-item.json' with { type: 'json' }
import sankey_chart from './chart/sankey-chart/registry-item.json' with { type: 'json' }
import data_point from './business/data-point/registry-item.json' with { type: 'json' }
import point_table from './business/point-table/registry-item.json' with { type: 'json' }
import table_select from './business/table-select/registry-item.json' with { type: 'json' }
import liquid_level from './business/liquid-level/registry-item.json' with { type: 'json' }
import node_tree_select from './business/node-tree-select/registry-item.json' with { type: 'json' }
import ruler_comp from './business/ruler-comp/registry-item.json' with { type: 'json' }
import network_graph from './business/network-graph/registry-item.json' with { type: 'json' }
import compute_statuses from './business/compute-statuses/registry-item.json' with { type: 'json' }
import data_point_panel from './business/data-point-panel/registry-item.json' with { type: 'json' }
import table_data_select from './business/table-data-select/registry-item.json' with { type: 'json' }
import bar from './business/bar/registry-item.json' with { type: 'json' }
import compute_status from './business/compute-status/registry-item.json' with { type: 'json' }
import data_point_input from './business/data-point-input/registry-item.json' with { type: 'json' }
import mobile_picker from './mobile/mobile-picker/registry-item.json' with { type: 'json' }
import mobile_scan_qr from './mobile/mobile-scan-qr/registry-item.json' with { type: 'json' }
import mobile_list from './mobile/mobile-list/registry-item.json' with { type: 'json' }
import mobile_calendar from './mobile/mobile-calendar/registry-item.json' with { type: 'json' }
import mobile_nav_bar from './mobile/mobile-nav-bar/registry-item.json' with { type: 'json' }
import mobile_date_picker from './mobile/mobile-date-picker/registry-item.json' with { type: 'json' }
import mobile_location from './mobile/mobile-location/registry-item.json' with { type: 'json' }
import mobile_popup from './mobile/mobile-popup/registry-item.json' with { type: 'json' }
import mobile_tab_bar from './mobile/mobile-tab-bar/registry-item.json' with { type: 'json' }
import view_warning from './view/view-warning/registry-item.json' with { type: 'json' }
import view_data_aggregate from './view/view-data-aggregate/registry-item.json' with { type: 'json' }
import view_filter from './view/view-filter/registry-item.json' with { type: 'json' }
import view_report from './view/view-report/registry-item.json' with { type: 'json' }
import view_actions from './view/view-actions/registry-item.json' with { type: 'json' }
import view_advanced_filter from './view/view-advanced-filter/registry-item.json' with { type: 'json' }
import view_pagination from './view/view-pagination/registry-item.json' with { type: 'json' }
import view_batch_command from './view/view-batch-command/registry-item.json' with { type: 'json' }
import view_batch_operation from './view/view-batch-operation/registry-item.json' with { type: 'json' }
import view_detail from './view/view-detail/registry-item.json' with { type: 'json' }
import view_log from './view/view-log/registry-item.json' with { type: 'json' }
import view_operation from './view/view-operation/registry-item.json' with { type: 'json' }
import view_data_table from './view/view-data-table/registry-item.json' with { type: 'json' }
import view_user from './view/view-user/registry-item.json' with { type: 'json' }
import view_model from './view/view-model/registry-item.json' with { type: 'json' }
import react_widget from './containers/react-widget/registry-item.json' with { type: 'json' }
import connect_widget from './containers/connect-widget/registry-item.json' with { type: 'json' }
import slot_container from './containers/slot-container/registry-item.json' with { type: 'json' }
import resource_container from './containers/resource-container/registry-item.json' with { type: 'json' }
import layout_container from './containers/layout-container/registry-item.json' with { type: 'json' }
import link from './containers/link/registry-item.json' with { type: 'json' }
import app_page from './containers/app-page/registry-item.json' with { type: 'json' }
import iteration from './containers/iteration/registry-item.json' with { type: 'json' }
import slot from './containers/slot/registry-item.json' with { type: 'json' }
import resource from './containers/resource/registry-item.json' with { type: 'json' }
import map_container from './gis/map-container/registry-item.json' with { type: 'json' }
import warn_views from './gis/warn-views/registry-item.json' with { type: 'json' }
import playback_view from './gis/playback-view/registry-item.json' with { type: 'json' }
import polygon_views from './gis/polygon-views/registry-item.json' with { type: 'json' }
import polygon_split from './gis/polygon-split/registry-item.json' with { type: 'json' }
import table_views from './gis/table-views/registry-item.json' with { type: 'json' }
import custom_views from './gis/custom-views/registry-item.json' with { type: 'json' }
import code_editor_views from './gis/code-editor-views/registry-item.json' with { type: 'json' }
import tool_views from './gis/tool-views/registry-item.json' with { type: 'json' }

export const blocks = [
    svg as RegistryItem,
    led_number as RegistryItem,
    svg_editor as RegistryItem,
    text_editor as RegistryItem,
    widgets_media as RegistryItem,
    qrcode as RegistryItem,
    time as RegistryItem,
    show_attachment as RegistryItem,
    upload_attachment as RegistryItem,
    flop_number as RegistryItem,
    widget_pdf_preivew as RegistryItem,
    custom_pagination as RegistryItem,
    player as RegistryItem,
    model_3d_geometry_cylinder as RegistryItem,
    model_3d_card as RegistryItem,
    model_3d_geometry_sphere as RegistryItem,
    model_3d_mesh as RegistryItem,
    model_3d_points as RegistryItem,
    model_3d_layout_3d as RegistryItem,
    model_3d_geometry_plane as RegistryItem,
    model_3d_geometry_cone as RegistryItem,
    model_3d_geometry_box as RegistryItem,
    model_3d_geometry_circle as RegistryItem,
    model_3d as RegistryItem,
    model_3d_geometry_tube as RegistryItem,
    video_widget as RegistryItem,
    button_widget as RegistryItem,
    video_periods_widget as RegistryItem,
    time_axis as RegistryItem,
    isc_video as RegistryItem,
    review_view_components as RegistryItem,
    form_widget as RegistryItem,
    form as RegistryItem,
    time_widget as RegistryItem,
    schema_form as RegistryItem,
    form_date_range as RegistryItem,
    form_date as RegistryItem,
    form_slider as RegistryItem,
    user_form_widget as RegistryItem,
    form_area as RegistryItem,
    form_rate as RegistryItem,
    table_schema_form as RegistryItem,
    form_switch as RegistryItem,
    form_checkbox as RegistryItem,
    form_input as RegistryItem,
    form_input_number as RegistryItem,
    form_upload as RegistryItem,
    form_radio as RegistryItem,
    form_map as RegistryItem,
    form_select as RegistryItem,
    warning_button as RegistryItem,
    reg_widget_component as RegistryItem,
    logout_component as RegistryItem,
    warning_audio as RegistryItem,
    new_menu as RegistryItem,
    warning_bar as RegistryItem,
    auth_info_cards as RegistryItem,
    scale_button as RegistryItem,
    service_time as RegistryItem,
    log_out as RegistryItem,
    message as RegistryItem,
    front_menu as RegistryItem,
    nav_tabs as RegistryItem,
    profile as RegistryItem,
    warning_notification as RegistryItem,
    user_menu as RegistryItem,
    user_name as RegistryItem,
    load_component as RegistryItem,
    language_change_widget as RegistryItem,
    change_password as RegistryItem,
    log_table_widget as RegistryItem,
    chart_radar as RegistryItem,
    chart_bar as RegistryItem,
    data_view_chart as RegistryItem,
    chart_map as RegistryItem,
    chart_line as RegistryItem,
    chart_gauge as RegistryItem,
    chart_pie as RegistryItem,
    report_reportwidget as RegistryItem,
    chart_pictorial_bar as RegistryItem,
    chart_mix as RegistryItem,
    chart_scatter as RegistryItem,
    chart_liquid_fill as RegistryItem,
    sankey_chart as RegistryItem,
    data_point as RegistryItem,
    point_table as RegistryItem,
    table_select as RegistryItem,
    liquid_level as RegistryItem,
    node_tree_select as RegistryItem,
    ruler_comp as RegistryItem,
    network_graph as RegistryItem,
    compute_statuses as RegistryItem,
    data_point_panel as RegistryItem,
    table_data_select as RegistryItem,
    bar as RegistryItem,
    compute_status as RegistryItem,
    data_point_input as RegistryItem,
    mobile_picker as RegistryItem,
    mobile_scan_qr as RegistryItem,
    mobile_list as RegistryItem,
    mobile_calendar as RegistryItem,
    mobile_nav_bar as RegistryItem,
    mobile_date_picker as RegistryItem,
    mobile_location as RegistryItem,
    mobile_popup as RegistryItem,
    mobile_tab_bar as RegistryItem,
    view_warning as RegistryItem,
    view_data_aggregate as RegistryItem,
    view_filter as RegistryItem,
    view_report as RegistryItem,
    view_actions as RegistryItem,
    view_advanced_filter as RegistryItem,
    view_pagination as RegistryItem,
    view_batch_command as RegistryItem,
    view_batch_operation as RegistryItem,
    view_detail as RegistryItem,
    view_log as RegistryItem,
    view_operation as RegistryItem,
    view_data_table as RegistryItem,
    view_user as RegistryItem,
    view_model as RegistryItem,
    react_widget as RegistryItem,
    connect_widget as RegistryItem,
    slot_container as RegistryItem,
    resource_container as RegistryItem,
    layout_container as RegistryItem,
    link as RegistryItem,
    app_page as RegistryItem,
    iteration as RegistryItem,
    slot as RegistryItem,
    resource as RegistryItem,
    map_container as RegistryItem,
    warn_views as RegistryItem,
    playback_view as RegistryItem,
    polygon_views as RegistryItem,
    polygon_split as RegistryItem,
    table_views as RegistryItem,
    custom_views as RegistryItem,
    code_editor_views as RegistryItem,
    tool_views as RegistryItem,
] as RegistryItem[]
