// Auto-generated by generate_module_indexes.py
import tabs from './ui/tabs/registry-item.json' with { type: 'json' }
import iframe from './ui/iframe/registry-item.json' with { type: 'json' }
import radio from './ui/radio/registry-item.json' with { type: 'json' }
import card from './ui/card/registry-item.json' with { type: 'json' }
import panel from './ui/panel/registry-item.json' with { type: 'json' }
import input from './ui/input/registry-item.json' with { type: 'json' }
import date from './ui/date/registry-item.json' with { type: 'json' }
import text_area from './ui/text-area/registry-item.json' with { type: 'json' }
import checkbox from './ui/checkbox/registry-item.json' with { type: 'json' }
import slider from './ui/slider/registry-item.json' with { type: 'json' }
import html from './ui/html/registry-item.json' with { type: 'json' }
import image from './ui/image/registry-item.json' with { type: 'json' }
import popover from './ui/popover/registry-item.json' with { type: 'json' }
import button from './ui/button/registry-item.json' with { type: 'json' }
import table from './ui/table/registry-item.json' with { type: 'json' }
import switch_component from './ui/switch/registry-item.json' with { type: 'json' }
import text from './ui/text/registry-item.json' with { type: 'json' }
import select from './ui/select/registry-item.json' with { type: 'json' }
import my_card from './ui/my-card/registry-item.json' with { type: 'json' }
import modal from './ui/modal/registry-item.json' with { type: 'json' }

export const components = [
    tabs as RegistryItem,
    iframe as RegistryItem,
    radio as RegistryItem,
    card as RegistryItem,
    panel as RegistryItem,
    input as RegistryItem,
    date as RegistryItem,
    text_area as RegistryItem,
    checkbox as RegistryItem,
    slider as RegistryItem,
    html as RegistryItem,
    image as RegistryItem,
    popover as RegistryItem,
    button as RegistryItem,
    table as RegistryItem,
    switch_component as RegistryItem,
    text as RegistryItem,
    select as RegistryItem,
    my_card as RegistryItem,
    modal as RegistryItem,
] as RegistryItem[]
