// Auto-generated by generate_module_indexes.py
import { blocks } from './blocks'

export const registry = {
  name: 'Airiot UI Library',
  homepage: 'https://airiot.cn/ui',
  items: [
    ...blocks,
  ],
}
