// typecheck

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { registry } from '../src/registry/index.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const registryPath = path.join(__dirname, '..', 'public', 'r', 'registry.json')

// Ensure public/r directory exists
const publicDir = path.join(__dirname, '..', 'public')
const registryDir = path.join(publicDir, 'r')

// Clean and recreate public/r directory
if (fs.existsSync(registryDir)) {
  fs.rmSync(registryDir, { recursive: true, force: true })
}
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true })
}
fs.mkdirSync(registryDir, { recursive: true })

// Process registry items to add file contents
const processedItems = registry.items
  .filter((item) => item.type !== 'registry:example')
  .map((item) => {
    const processedFiles = item.files.map((file: any) => {
      const filePath = path.join(__dirname, '..', 'src', 'registry', file.path)

      // Read file content
      let content = ''
      if (fs.existsSync(filePath)) {
        content = fs.readFileSync(filePath, 'utf-8')
      }

      return {
        ...file,
        content,
      }
    })

    // Create individual component JSON file
    const componentJson = {
      ...item,
      files: processedFiles,
    }
    const componentJsonPath = path.join(registryDir, `${item.name}.json`)
    fs.writeFileSync(componentJsonPath, JSON.stringify(componentJson, null, 2))

    return {
      ...item,
      files: processedFiles,
    }
  })

const cleanedRegistry = {
  $schema: 'https://ui.shadcn.com/schema/registry.json',
  ...registry,
  items: processedItems,
}

fs.writeFileSync(registryPath, JSON.stringify(cleanedRegistry, null, 2))

console.log(`✓ Registry built successfully at ${registryPath}`)

// Create a registry index file for use by ComponentPreview in the app.
const registryIndex = `
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index = {
  "default": {
    ${registry.items
      .filter((item) => item.type === 'registry:example')
      .map((item) => {
        const componentFile = item.files.find((file) => file.path.endsWith('.tsx'))

        return `
    "${item.name}": {
      component: ${componentFile ? `React.lazy(() => import("@/${componentFile.path}"))` : 'null'},
    }
    `
      })}
  },
} as const
`

const registryIndexPath = path.join(__dirname, '..', '__registry__', 'index.tsx')
const registryIndexDir = path.dirname(registryIndexPath)

if (!fs.existsSync(registryIndexDir)) {
  fs.mkdirSync(registryIndexDir, { recursive: true })
}

fs.writeFileSync(registryIndexPath, registryIndex)

console.log(`✓ Registry index built successfully at ${registryIndexPath}`)
console.log(`✓ Total items: ${cleanedRegistry.items.length}`)
