
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mjs
// Do not edit this file directly.
import * as React from "react"

export const Index = {
  "default": {
    
  },
} as const
